##服务配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
  servlet:
    context-path: /opensource-arche-generator
    encoding:
      charset: UTF-8
      force: true
      enabled: true
##日志配置
logging:
  config: classpath:config/spring/springBoot-logbak-local.xml
##spring生态配置
spring:
  ##应用名
  application:
      name: buukle-generator
  devtools:
    add-properties: false
  ##thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/generator/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  ##datasource
  datasource:
    url: jdbc:mysql://mysql.buukle.top:13306/opensource-arche-generator?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: A987654321b/
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化，最小，最大连接数
    initialSize: 3
    minIdle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
  #支持multipart file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:/config/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl